version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: raw data ads on adwords
        columns:
           - name: date_date
             tests:
              - not_null
           - name: paid_source
             tests:
              - not_null
           - name: campaign_key
             tests:
              - not_null
           - name: camPGN_name
             tests:
              - not_null
           - name: ads_cost
             tests:
              - not_null
           - name: impression
             tests:
              - not_null
           - name: click
             tests:
              - not_null
           - name: "(date_date ||'-'|| campaign_key)"
             description: Primary Key
             tests:
              - unique
      - name: bing
        identifier: raw_gz_bing
        description: raw data ads on bing
        columns:
          - name: date_date
            tests:
              - not_null
          - name: paid_source
            tests:
              - not_null
          - name: campaign_key
            tests:
              - not_null
          - name: camPGN_name
            tests:
              - not_null
          - name: ads_cost
            tests:
              - not_null
          - name: impression
            tests:
              - not_null
          - name: click
            tests:
              - not_null
          - name: "(date_date ||'-'|| campaign_key)"
            description: Primary Key
            tests:
              - unique
      - name: criteo
        identifier: raw_gz_criteo
        description: raw data ads on criteo
        columns:
           - name: date_date
             tests:
              - not_null
           - name: paid_source
             tests:
              - not_null
           - name: campaign_key
             tests:
              - not_null
           - name: camPGN_name
             tests:
              - not_null
           - name: ads_cost
             tests:
              - not_null
           - name: impression
             tests:
              - not_null
           - name: click
             tests:
              - not_null
           - name: "(date_date ||'-'|| campaign_key)"
             description: Primary Key
             tests:
              - unique
      - name: facebook
        identifier: raw_gz_facebook
        description: raw data ads on facebook
        tests:
         - unique: 
              column_name: "(date_date ||'-'|| campaign_key)"
         - not_null:
              column_name: date_date
         - not_null:
              column_name: paid_source
         - not_null:
              column_name: campaign_key
         - not_null:
              column_name: camPGN_name
         - not_null:
              column_name: ads_cost
         - not_null:
              column_name: impression
         - not_null:
              column_name: click
      - name: product
        identifier: raw_gz_product
        description: product list of Greenweez / one product_id per row with the respective purchase_price of that product
        columns:
          - name: products_id
            description: unique products_id used as Primary Key
            tests:
              - unique
          - name: purchase_price
            description: the purchase price of the respective product
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        loaded_at_field: "CAST (date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            period: day
            count: 90
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: the id of the order made
          - name: products_id
            description: listing of each item ordered in the placed order / can be several product_ids per order_id
          - name: revenue
            description: the revenue generated per product sold each orders
          - name: quantity
            description: the quantity that each product was ordered in each order
      - name: ship
        identifier: raw_gz_ship
        description: one row per order_id / with its respecctive shipping costs and shipping revenues of fulfilling the order
        columns:
          - name: orders_id
            description: the unique id of every order placed / one row per order
            tests:
              - unique
          - name: shipping_fee
            description: the shipping fee each customer pays us to fulfill their order
          - name: logcost
            description: the logistic costs that the company pays for fulfilling each order
          - name: ship_cost
            description: the shipping costs that the company pays for fulfilling each order
models:
  - name: int_orders_margin
    description: margin per order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
      - name: margin
        description: (revenue - purchase_costs) per order
        tests:
          - not_null
      - name: purchase_cost
        description: (quantity * purchase_price) per order
        tests:
          - not_null
  - name: int_orders_operational
    description: operational margin per order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
      - name: purchase_cost
        description: purchase costs per order
        tests:
          - not_null
      - name: operational_margin
        description: operational margin per order
        tests:
          - not_null
  - name: int_sales_margin
    description: margin per product sold
  - name: finance_days
    description: all the data calculated per day for the finance team
    columns:
      - name: date_date
        description: primary key
        tests:
          - unique
      - name: operational_margin_per_day
        description: see column's name!
        tests:
          - not_null
  - name: int_campaigns
    description: joined all ads tables together
    tests:
         - unique: 
              column_name: "(date_date ||'-'|| campaign_key)"
         - not_null:
              column_name: date_date
         - not_null:
              column_name: paid_source
         - not_null:
              column_name: campaign_key
         - not_null:
              column_name: campaign_name
         - not_null:
              column_name: ads_cost
         - not_null:
              column_name: impression
         - not_null:
              column_name: click
  - name: int_campaigns_day
    description: all campaign data per day
    tests:
         - unique: 
              column_name: date_date
         - not_null:
              column_name: date_date
         - not_null:
              column_name: ads_cost_per_day
         - not_null:
              column_name: ads_impression_per_day
         - not_null:
              column_name: ads_clicks_per_day
  - name: finance_campaigns_day
    description: all financial data joined with all campaigns data per day
    tests:
      - unique: 
          column_name: date_date
      - not_null:
              column_name: date_date
      - not_null:
              column_name: average_basket
      - not_null:
              column_name: operational_margin_per_day
      - not_null:
              column_name: ads_margin
      - not_null:
              column_name: total_quantity_sold_per_day
      - not_null:
              column_name: ads_cost_per_day
      - not_null:
              column_name: ads_impression_per_day
      - not_null:
              column_name: ads_clicks_per_day
      - not_null:
              column_name: revenue_per_day
      - not_null:
              column_name: purchase_cost_per_day
      - not_null:
              column_name: margin_per_day
      - not_null:
              column_name: shipping_fee_per_day
      - not_null:
              column_name: logcost_per_day
      - not_null:
              column_name: ship_cost

      
